/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HTMLToTrees;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.net.URL;

/**
 *
 * @author user
 */
public class Link extends javax.swing.JFrame {

    /**
     * Creates new form inicioo
     */
    Link() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/tree.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linkh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML to trees");
        setMinimumSize(new java.awt.Dimension(900, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTINUE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 320, 120, 30);

        linkh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkhActionPerformed(evt);
            }
        });
        getContentPane().add(linkh);
        linkh.setBounds(110, 240, 660, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/link2_1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(930, 700));
        jLabel1.setMinimumSize(new java.awt.Dimension(930, 700));
        jLabel1.setPreferredSize(new java.awt.Dimension(930, 700));
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 920, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkhActionPerformed
        Enter();
    }//GEN-LAST:event_linkhActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Enter();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField linkh;
    // End of variables declaration//GEN-END:variables

    private void Enter() {
        Html object = new Html();
        if (!urlValida(linkh.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid link", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            object.link = this.linkh.getText();
            new Vista().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }

    private boolean urlValida(String url) {     //Función para validar URL
        try {
            (new URL(url)).openStream().close();
            return true;
        } catch (Exception e) {
        }
        return false;
    }
}
