/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HTMLToTrees;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author F-E-R
 */
public class Vista extends javax.swing.JFrame {

    private boolean creado;

    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        vistaPn.setPreferredSize(new Dimension(1000, 1000));
        creado = false;
        ButtonTransparent();
        devolver.setEnabled(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/tree.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        verBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vistaPn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        devolver = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML to trees");
        setResizable(false);

        verBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eye (2).png"))); // NOI18N
        verBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        vistaPn.setBackground(new java.awt.Color(222, 208, 174));
        vistaPn.setPreferredSize(new java.awt.Dimension(500, 500));
        vistaPn.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                vistaPnAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout vistaPnLayout = new javax.swing.GroupLayout(vistaPn);
        vistaPn.setLayout(vistaPnLayout);
        vistaPnLayout.setHorizontalGroup(
            vistaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        vistaPnLayout.setVerticalGroup(
            vistaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(vistaPn);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/inicio.png"))); // NOI18N

        devolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/devolver.png"))); // NOI18N
        devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(verBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(verBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonTransparent() {
        verBtn.setOpaque(false);
        verBtn.setContentAreaFilled(false);
        verBtn.setBorderPainted(false);
        devolver.setOpaque(false);
        devolver.setContentAreaFilled(false);
        devolver.setBorderPainted(false);

    }

    private void verBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBtnActionPerformed
        if (!creado) {
            try {
                Html.main();
            } catch (IOException ex) {
                Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
            }
            creado = true;
        }
        dibujar();
        devolver.setEnabled(true);
    }//GEN-LAST:event_verBtnActionPerformed

    private void vistaPnAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_vistaPnAncestorMoved
        if (creado) {
            dibujar();
        }
    }//GEN-LAST:event_vistaPnAncestorMoved

    private void devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverActionPerformed
        this.setVisible(false);
        new Link().setVisible(true);
    }//GEN-LAST:event_devolverActionPerformed

    /**
     * @param args the command line arguments
     */
    private void dibujar() {
        Graphics g = vistaPn.getGraphics();
        /*Inicializando variable que controla la coordenada vertical de la pantalla*/
        int y = 30;
        for (int i = 0; i < Html.arbolito.Altura(Html.arbolito.getRaiz()); i++) {
            /*Para cada nivel del arbol se extrae la informacion de los nodos*/
            String[] nodos = Html.arbolito.getInfo_nivel(Html.arbolito.getRaiz(), i);
            /*Horizontalmente la pantalla se divide en la cantidad de nodos del nivel + 1*/
            int x = (getWidth() - 20) / (Html.arbolito.getNodos_nivel(Html.arbolito.getRaiz(), i) + 1);
            for (int j = 0; j < Html.arbolito.getNodos_nivel(Html.arbolito.getRaiz(), i); j++) {
                /*A cada nodo del nivel se le establecen sus coordendas*/
                Html.arbolito.establecer_coordenadas(Html.arbolito.getRaiz(), nodos[j], (x * (j + 1)), y);
                /*Variable para el tamaño horizontal del óvalo del nodo*/
                int x_oval = nodos[j].length() * 10;
                if (x_oval > 60) {
                    /*Pintando los ovalos*/
                    g.setColor(new Color(176, 210, 151));
                    g.fillOval((x * (j + 1)), y, x_oval, 20);
                    g.setColor(new Color(0, 0, 0));
                    g.drawOval((x * (j + 1)), y, x_oval, 20);
                } else {
                    /*Pintando los ovalos*/
                    g.setColor(new Color(176, 210, 151));
                    g.fillOval((x * (j + 1)), y, 60, 20);
                    g.setColor(new Color(0, 0, 0));
                    g.drawOval((x * (j + 1)), y, 60, 20);
                }
                g.setColor(new Color(0, 0, 0));
                /*Pintando la información del nodo*/
                g.drawString(Html.arbolito.escribir_nodo(nodos[j]), (x * (j + 1)) + 25, y + 15);
                if (i != 0) {
                    /*Obteniendo el nodo padre del nodo recien pintado para conectar los ovalos con la linea*/
                    Nodo temp = (Nodo) Html.arbolito.hijoypadre.get(nodos[j]);
                    /*Pintando la linea desde el nodo recien pintado hasta el nodo padre del mismo*/
                    g.drawLine((int) temp.punto.getX() + 30, (int) temp.punto.getY() + 20, (x * (j + 1)) + 30, y);
                }
            }
            y += 70; // cambiando la coordenada vertical
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio inicio = new Inicio();
                inicio.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton devolver;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton verBtn;
    private javax.swing.JPanel vistaPn;
    // End of variables declaration//GEN-END:variables
}
