/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbol_n.ario;

import javax.swing.JOptionPane;
import arbol_n.ario.Html;
/**
 *
 * @author user
 */
public class linkk extends javax.swing.JFrame {

    /**
     * Creates new form inicioo
     */
    linkk() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linkh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 675));
        setMinimumSize(new java.awt.Dimension(900, 675));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ENTER PARA CONTINUAR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 320, 310, 30);

        linkh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        linkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkhActionPerformed(evt);
            }
        });
        getContentPane().add(linkh);
        linkh.setBounds(160, 240, 660, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/link_1.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -30, 980, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkhActionPerformed
        Enter();
    }//GEN-LAST:event_linkhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField linkh;
    // End of variables declaration//GEN-END:variables



    public void Enter() {
        
        Html object = new Html();
        
        if (this.linkh.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo vacio", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            object.link = this.linkh.getText();
            new vista().setVisible(true);
            this.setVisible(false);
            this.dispose();
        }

    }
}
