/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbol_n.ario;

import java.awt.Graphics;
import java.awt.Point;
import java.util.HashMap;

/**
 *
 * @author F-E-R
 */
public class vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        verBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vistaPn = new javax.swing.JPanel();
        creararbolBtn = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        verBtn.setText("Ver");
        verBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(10000, 10000));

        vistaPn.setPreferredSize(new java.awt.Dimension(2000, 1500));

        javax.swing.GroupLayout vistaPnLayout = new javax.swing.GroupLayout(vistaPn);
        vistaPn.setLayout(vistaPnLayout);
        vistaPnLayout.setHorizontalGroup(
            vistaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        vistaPnLayout.setVerticalGroup(
            vistaPnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(vistaPn);

        creararbolBtn.setText("Crear arbol");
        creararbolBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creararbolBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(verBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(creararbolBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creararbolBtn)
                    .addComponent(verBtn))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBtnActionPerformed
        dibujar(tree.getRaiz(),getWidth()/2,30,getWidth()/5);
    }//GEN-LAST:event_verBtnActionPerformed

    private void creararbolBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creararbolBtnActionPerformed
        
        tree.Insertar(tree.getRaiz(), "1", "0");
        tree.Insertar(tree.getRaiz(), "2", "0");
        tree.Insertar(tree.getRaiz(), "3", "0");
        tree.Insertar(tree.getRaiz(), "1.1", "1");
        tree.Insertar(tree.getRaiz(), "1.2", "1");
        tree.Insertar(tree.getRaiz(), "2.1", "2");
        tree.Insertar(tree.getRaiz(), "2.2", "2");
        tree.Insertar(tree.getRaiz(), "2.3", "2");
        tree.Insertar(tree.getRaiz(), "3.1", "3");
        tree.Insertar(tree.getRaiz(), "3.2", "3");

        tree.recorrerarbol(tree.getRaiz());
//        System.out.println(tree.Altura(tree.getRaiz()) + "");
//
        System.out.println("----NIVELES-----");
        System.out.println(tree.getNodos_nivel(tree.getRaiz(), 2));
//
//        System.out.println("-----HIJO Y PADRE-----");
//        Nodo temp = (Nodo) tree.hijoypadre.get("3.1");
//        System.out.println(temp.getInfo());

        
        for (int i = 0; i < tree.Altura(tree.getRaiz()); i++) {
            espacioHor[i] = tree.getNodos_nivel(tree.getRaiz(), i);
        }
    }//GEN-LAST:event_creararbolBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private int radio = 15, c = 0;
    private int espacioVer = tree.Altura(tree.getRaiz()) * 10;
    private HashMap coordenadas = new HashMap();
    private static int espacioHor[] = new int [1000];
    private static Arbol tree = new Arbol("0");
    

    private void dibujar(Nodo nodo, int x, int y, int espacioH){
        Graphics g = vistaPn.getGraphics();
        g.drawOval(x-radio, y-radio, 2*radio, 2*radio);
        g.drawString(nodo.getInfo(), x-6, y+4);
        coordenadas.put(nodo, new Point(x,y));
        for (int i = 0; i < nodo.getCanhijos(); i++) {
            Point punto = (Point) coordenadas.get(nodo.hijos[i]);
            linea(x-espacioH, y+espacioVer, punto.x, punto.y);
            dibujar(nodo.hijos[i], x-espacioH, y+espacioVer, espacioH/tree.getNodos_nivel(tree.getRaiz(), c++));
            x +=espacioH;
        }
    }
    
    private void linea(int x1, int y1, int x2, int y2){
        Graphics g = vistaPn.getGraphics();
        
        double  d=Math.sqrt(espacioVer*espacioVer+(x2-x1)*(x2-x1));
        int xx1=(int)(x1-radio*(x1-x2)/d);
        int yy1=(int)(y1-radio*(y1-y2)/d);
        int xx2=(int)(x2+radio*(x1-x2)/d);
        int yy2=(int)(y2+radio*(y1-y2)/d);

        g.drawLine(xx1,yy1,xx2,yy2);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creararbolBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton verBtn;
    private javax.swing.JPanel vistaPn;
    // End of variables declaration//GEN-END:variables
}
